name: linux
on: [push]
jobs:

  build:
    name: build
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        go: [ '1.18', '1.17', '1.16', '1.15', '1.14', '1.13' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Go version
      run: go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...